language: php

env:
  - APP_ENV=travis

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  ## Database
  - mysql -e 'create database my_dbname;'

script:
  - phpunit
